site_name: TBPX Module Assembly and Testing - Firenze
site_url: https://bardellig.github.io/TBPX-FI-Module-Docs/
use_directory_urls: false
theme:
  name: material  # or 'cayman' if using mkdocs-cayman
extra_css: []
extra_javascript: []
nav:
  - Home: index.md
  - IV Bare Module Testing:
      - Procedure: iv_bare_module_testing/IT_3D_IV_BM_procedure.md
  - Preliminary Operations:
      - Overview: module_testing_preliminary/preliminary_op.md
  - Module Testing:
      - Overview: module_testing/codi.md
